// components/content/Gist.vue
<template>
  <Head>
    <Link
      rel="stylesheet"
      href="https://cdn.rawgit.com/lonekorean/gist-syntax-themes/848d6580/stylesheets/monokai.css"
    />
  </Head>
  <!-- eslint-disable-next-line vue/no-v-html -->
  <div v-if="!loading" class="gist-el-root" v-html="ghSrc" />
</template>

<script setup lang="ts">
import uniqid from "uniqid";

const props = defineProps<{
  id: string;
  file?: string;
}>();

const attachedStyles = ref(false);
const loading = ref(true);
const ghSrc = ref("");

const styling = `
.js-file-line-container > tbody > tr {
  border-bottom-width: 0px !important;
}

[class=dark] .gist .gist-data {
  background-color: #262626 !important;
  border-color: #4e4e4e !important;
}

[class=dark] .gist {
  color: #ddd;
}

[class=dark] .gist .gist-meta {
    color: #d8d8d8;
    background-color: #292929 !important;
}

[class=dark] .gist .gist-meta a {
  color: #ddd;
}

[class=dark] .gist .gist-file {
  border-color: #4e4e4e #4e4e4e #5e5e5e !important;
}

.gist .gist-file article {
  padding: 1rem !important;
}

[class=dark] .gist .blob-num:hover {
  color: rgb(145 148 150 / 60%) !important;
}

.gist-el-root .gist .markdown-body code::before {
  content: "" !important;
}

.gist-el-root .gist .markdown-body code::after {
  content: "" !important;
}

.gist-el-root .gist .markdown-body h1 {
  margin-bottom: 1.35rem;
}

.gist-el-root .gist .markdown-body h2 {
  margin-bottom: 1.1rem;
}

.gist-el-root .gist .markdown-body h3 {
  margin-bottom: 0.95rem;
}

.gist-meta .Link--inTextBlock {
  text-decoration-style: dashed !important;
}

.gist-meta .Link--inTextBlock:hover {
  text-decoration: underline !important;
  text-decoration-style: dashed !important;
}
`;

const runtimeConfig = useRuntimeConfig();
const gistCallbackId = `gistCallback_${props.id}_${uniqid("gh")}`;

onMounted(() => {
  if (!runtimeConfig.nitro) {
    // client-side only
    const script = document.createElement("script");

    const initUrl = `https://gist.github.com/${props.id}.json?callback=${gistCallbackId}`;
    const fileUrl = props.file ? `&file=${props.file}` : "";

    script.type = "text/javascript";
    script.src = `${initUrl}${fileUrl}`;

    // @ts-expect-error fuck you
    window[gistCallbackId] = (gistContent: { div: string; stylesheet: string }) => {
      loading.value = false;
      ghSrc.value = gistContent.div;

      if (!attachedStyles.value) {
        attachedStyles.value = true;

        const link = document.createElement("link");

        link.type = "text/css";
        link.rel = "stylesheet";
        link.href = gistContent.stylesheet;

        document.head.appendChild(link);
      }

      try {
        // @ts-expect-error fuck me
        delete window[gistCallbackId];
      } catch {}
    };

    document.body.appendChild(script);

    // Attach styling
    if (!document.querySelector("style[data-gist-style]")) {
      const styleSheets = document.createElement("style");
      styleSheets.setAttribute("data-gist-style", "1");

      styleSheets.innerHTML = styling;
      document.head.appendChild(styleSheets);
    }
  }
});
</script>

// components/shortcode/gist.tsx
import Head from 'next/head';
import React from 'react';

interface EmbedGistProps {
  id: string;
  file?: string;
}

interface EmbedGistState {
  loading: boolean;
  src: string;
}

// Each time we request a Gist, we’ll need to generate a new
// global function name to serve as the JSONP callback.
let gistCallbackId = 0;

class EmbeddedGist extends React.Component<EmbedGistProps, EmbedGistState> {
  stylesheetAdded: boolean;
  id: string;
  file?: string;

  static nextGistCallback() {
    return 'embed_gist_callback_' + gistCallbackId++;
  }

  constructor(props: EmbedGistProps) {
    super(props);
    this.addStylesheet = this.addStylesheet.bind(this);
    this.id = props.id;
    this.file = props.file;
    this.stylesheetAdded = false;
    this.state = {
      loading: true,
      src: '',
    };
  }

  // The Gist JSON data includes a stylesheet to add to the page
  // to make it look correct. `addStylesheet` ensures we only add
  // the stylesheet one time.
  addStylesheet(href: string) {
    if (!this.stylesheetAdded) {
      this.stylesheetAdded = true;
      const link = document.createElement('link');
      link.type = 'text/css';
      link.rel = 'stylesheet';
      link.href = href;

      document.head.appendChild(link);
    }
  }

  componentDidMount() {
    // Create a JSONP callback that will set our state
    // with the data that comes back from the Gist site
    const gistCallback = EmbeddedGist.nextGistCallback();
    window[gistCallback] = function (gist) {
      this.setState({
        loading: false,
        src: gist.div,
      });
      this.addStylesheet(gist.stylesheet);
    }.bind(this);
    let url = 'https://gist.github.com/' + this.props.id + '.json?callback=' + gistCallback;
    if (this.props.file) {
      url += '&file=' + this.props.file;
    }
    // Add the JSONP script tag to the document.
    const script = document.createElement('script');
    script.type = 'text/javascript';
    script.src = url;
    document.head.appendChild(script);
  }

  render() {
    if (this.state.loading) {
      return null;
    } else {
      return (
        <>
          <Head>
            <link
              href="https://cdn.rawgit.com/lonekorean/gist-syntax-themes/848d6580/stylesheets/monokai.css"
              rel="stylesheet"
            />
            {/* Override some styling */}
            <style>
              {`
                .js-file-line-container > tbody > tr {
                  border-bottom-width: 0px !important;
                }

                [class=dark] .gist .gist-data {
                  background-color: #262626 !important;
                  border-color: #4e4e4e !important;
                }

                [class=dark] .gist {
                  color: #ddd;
                }

                [class=dark] .gist .gist-meta {
                    color: #d8d8d8;
                    background-color: #292929 !important;
                }

                [class=dark] .gist .gist-meta a {
                  color: #ddd;
                }

                [class=dark] .gist .gist-file {
                  border-color: #4e4e4e #4e4e4e #5e5e5e !important;
                }

                .gist .gist-file article {
                  padding: 1rem !important;
                }
                
                [class=dark] .gist .blob-num:hover {
                  color: rgb(145 148 150 / 60%) !important;
                }
              `}
            </style>
          </Head>
          <div dangerouslySetInnerHTML={{ __html: this.state.src }} />
        </>
      );
    }
  }
}

export default EmbeddedGist;
