// pages/about.tsx
/* eslint-disable @next/next/no-img-element */
import siteMetadata from '@/data/siteMetadata.json';
import aboutData from '@/data/aboutData';
import SocialIcon from '@/components/social-icons';
import { PageSeo } from '@/components/SEO';

import { useIntl } from 'react-intl';

import { unified } from 'unified';
import linebreaks from 'remark-breaks';
import gemoji from 'remark-gemoji';
import markdown from 'remark-parse';
import html from 'remark-html';

function parseMarkdownSimple(inputText: string) {
  const result = unified()
    .use(gemoji)
    .use(linebreaks)
    .use(markdown)
    .use(html)
    .processSync(inputText);
  return result.toString();
}

function buildAboutPage(selectedIntl: string) {
  if (Array.isArray(aboutData)) {
    aboutData;
  }

  const allKeys = Object.keys(aboutData);
  if (!allKeys.includes(selectedIntl)) {
    return aboutData[allKeys[0]];
  }
  return aboutData[selectedIntl];
}

export default function About() {
  const intl = useIntl();

  const sectionsAbout = buildAboutPage(intl.locale);

  return (
    <>
      <PageSeo
        title={`${intl.formatMessage({ id: 'about' })} - ${siteMetadata.author}`}
        description={intl.formatMessage({ id: 'descAboutPage' }, { author: siteMetadata.author })}
      />
      <div className="divide-y">
        <div className="pt-6 pb-8 space-y-2 md:space-y-5">
          <h1 className="text-3xl font-extrabold leading-9 tracking-tight text-gray-900 dark:text-gray-100 sm:text-4xl sm:leading-10 md:text-6xl md:leading-14">
            {intl.formatMessage({ id: 'about' })}
          </h1>
        </div>
        <div className="items-start space-y-2 xl:grid xl:grid-cols-3 xl:gap-x-8 xl:space-y-0">
          <div className="flex flex-col items-center pt-8 space-x-2">
            <img src={siteMetadata.image} alt="avatar" className="w-48 h-48 rounded-full" />
            <h3 className="pt-4 pb-2 text-2xl font-bold leading-8 tracking-tight">
              {siteMetadata.author}
            </h3>
            <div className="text-gray-500 dark:text-gray-400 text-center">
              {intl.formatMessage({ id: 'tagLine' })}
            </div>
            <div className="flex pt-6 space-x-3">
              <SocialIcon kind="mail" href={`mailto:${siteMetadata?.email}`} />
              <SocialIcon kind="github" href={siteMetadata?.github} />
              <SocialIcon kind="twitter" href={siteMetadata?.twitter} />
              <SocialIcon kind="mastodon" href={siteMetadata?.mastodon} />
              <SocialIcon kind="donate" href={siteMetadata?.donate} />
            </div>
          </div>
          <div className="pt-8 pb-8 prose dark:prose-dark max-w-none xl:col-span-2">
            <p className="italic text-center">{intl.formatMessage({ id: 'siteDesc' })}</p>
            {sectionsAbout.map((section, ev) => {
              const parsedHTML = parseMarkdownSimple(section);
              return <p key={`sec-${ev}`} dangerouslySetInnerHTML={{ __html: parsedHTML }} />;
            })}
          </div>
        </div>
      </div>
    </>
  );
}

// pages/about.vue
<template>
  <div class="divide-y">
    <div class="space-y-2 pb-8 pt-6 md:space-y-5">
      <h1
        class="md:leading-14 font-variable text-3xl leading-9 tracking-tight text-gray-900 variation-weight-extrabold dark:text-gray-100 sm:text-4xl sm:leading-10 md:text-6xl"
      >
        {{ $t("nav.about") }}
      </h1>
    </div>
    <div class="items-start space-y-2 xl:grid xl:grid-cols-3 xl:gap-x-8 xl:space-y-0">
      <div class="flex flex-col items-center pt-8">
        <ImageWrap :src="blogConfig.aboutImage" class="h-48 w-48 rounded-full" alt="Avatar" />
        <h3 class="font-variable mx-0 pb-2 pt-4 text-2xl leading-8 tracking-tight variation-weight-bold">
          {{ blogConfig.title }}
        </h3>
        <div class="text-center text-gray-500 dark:text-gray-400">
          {{ blogConfig.description }}
        </div>
        <div class="flex flex-wrap space-x-3 pt-6">
          <SocialIcon
            v-for="socialMedia in aboutContent?.socialMedia ?? []"
            :key="socialMedia.kind"
            v-bind="socialMedia"
          />
          <SocialIcon kind="rss" :link="`/feeds/${locale}.xml`" alt="RSS" />
        </div>
      </div>
      <div v-if="aboutContent" class="prose max-w-none pb-8 pt-8 dark:prose-invert xl:col-span-2">
        <ContentRenderer :value="aboutContent">
          <ContentRendererMarkdown :value="aboutContent" />
        </ContentRenderer>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { ParsedContent } from "@nuxt/content";

interface SocialMedia {
  kind: "twitter" | "github" | "discord" | "misskey" | "mastodon" | "matrix" | "donation" | "email";
  link: string;
  alt?: string;
}

interface ParsedContentWithSocialMedia extends ParsedContent {
  socialMedia: SocialMedia[];
}

const { locale, t } = useI18n();

const blogConfig = useBlogConfig();

const { data: aboutContent } = await useAsyncData(`homeblog-about-page-about-${locale.value}`, () =>
  queryContent<ParsedContentWithSocialMedia>()
    .where({
      _source: "data",
      _id: `data:_data:${locale.value}:about.md`,
    })
    .findOne()
);

useBlogHead({
  title: t("nav.about"),
  description: t("desc.about"),
});
</script>
